# Generated by Django 5.2.13 on 2026-04-23 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('client_type', models.CharField(choices=[('private', 'Private'), ('corporate', 'Corporate')], default='private', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('preferred_contact', models.CharField(blank=True, max_length=80)),
                ('service_level', models.CharField(blank=True, max_length=20)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name', '-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_status_317d75_idx',
            old_name='crm_lead_status__eb26e9_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_service_064a52_idx',
            old_name='crm_lead_service_07e1d6_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_destina_4255ca_idx',
            old_name='crm_lead_destina_cbf7f8_idx',
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type', 'service_level'], name='crm_client_client__f9ad5e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='crm_client_name_c90dec_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='crm_client_company_19f044_idx'),
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.client'),
        ),
    ]
