# Generated by Django 5.2.13 on 2026-05-02 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_lifecycle_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(max_length=40, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('revision_requested', 'Revision Requested'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_name', models.CharField(max_length=180)),
                ('approver_email', models.EmailField(blank=True, max_length=254)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='crm.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('transfer', 'Transfer'), ('visa', 'Visa'), ('activity', 'Activity'), ('insurance', 'Insurance'), ('service_fee', 'Service Fee'), ('other', 'Other')], max_length=30)),
                ('supplier', models.CharField(blank=True, max_length=180)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_sell', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('research', 'Research'), ('quoted', 'Quoted'), ('held', 'Held'), ('confirmed', 'Confirmed'), ('unavailable', 'Unavailable')], default='research', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.quote')),
            ],
            options={
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['lead', 'status'], name='crm_quote_lead_id_03d0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='crm_quote_quote_n_eec884_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('lead', 'version'), name='unique_quote_version_per_lead'),
        ),
        migrations.AddIndex(
            model_name='quoteapproval',
            index=models.Index(fields=['quote', 'decision'], name='crm_quoteap_quote_i_0c2e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['quote', 'category'], name='crm_quoteli_quote_i_e6864a_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['status'], name='crm_quoteli_status_85fbdc_idx'),
        ),
    ]
