# Generated by Django 5.2.13 on 2026-05-02 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_quote_quoteapproval_quoteline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripItinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('in_travel', 'In Travel'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='crm.lead')),
            ],
            options={
                'ordering': ['lead', 'start_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('car', 'Car'), ('ferry', 'Ferry'), ('transfer', 'Transfer'), ('other', 'Other')], default='flight', max_length=20)),
                ('from_city', models.CharField(max_length=140)),
                ('to_city', models.CharField(max_length=140)),
                ('departure_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=180)),
                ('booking_status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='crm.tripitinerary')),
            ],
            options={
                'ordering': ['itinerary', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=140)),
                ('country', models.CharField(blank=True, max_length=140)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(default=0)),
                ('purpose', models.CharField(choices=[('leisure', 'Leisure'), ('business', 'Business'), ('transit', 'Transit'), ('event', 'Event'), ('extension', 'Extension')], default='leisure', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='crm.tripitinerary')),
            ],
            options={
                'ordering': ['itinerary', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='crm.itinerarystop')),
            ],
            options={
                'ordering': ['stop', 'start_at', 'title'],
                'indexes': [models.Index(fields=['stop', 'status'], name='crm_experie_stop_id_5a1adf_idx'), models.Index(fields=['category'], name='crm_experie_categor_1d598c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccommodationBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('lodge', 'Lodge'), ('villa', 'Villa'), ('apartment', 'Apartment'), ('camp', 'Camp'), ('cruise', 'Cruise'), ('other', 'Other')], default='hotel', max_length=20)),
                ('room_type', models.CharField(blank=True, max_length=160)),
                ('board_basis', models.CharField(blank=True, max_length=120)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('supplier', models.CharField(blank=True, max_length=180)),
                ('booking_status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('confirmation_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='crm.itinerarystop')),
            ],
            options={
                'ordering': ['stop', 'check_in', 'name'],
                'indexes': [models.Index(fields=['stop', 'booking_status'], name='crm_accommo_stop_id_748869_idx'), models.Index(fields=['name'], name='crm_accommo_name_2ffb59_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tripitinerary',
            index=models.Index(fields=['lead', 'status'], name='crm_tripiti_lead_id_b66cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='tripitinerary',
            index=models.Index(fields=['start_date', 'end_date'], name='crm_tripiti_start_d_21d1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='transportsegment',
            index=models.Index(fields=['itinerary', 'sequence_number'], name='crm_transpo_itinera_0335cb_idx'),
        ),
        migrations.AddIndex(
            model_name='transportsegment',
            index=models.Index(fields=['booking_status'], name='crm_transpo_booking_9bd7c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportsegment',
            constraint=models.UniqueConstraint(fields=('itinerary', 'sequence_number'), name='unique_transport_sequence_per_itinerary'),
        ),
        migrations.AddIndex(
            model_name='itinerarystop',
            index=models.Index(fields=['itinerary', 'sequence_number'], name='crm_itinera_itinera_db07fe_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarystop',
            index=models.Index(fields=['city', 'country'], name='crm_itinera_city_96c2fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerarystop',
            constraint=models.UniqueConstraint(fields=('itinerary', 'sequence_number'), name='unique_stop_sequence_per_itinerary'),
        ),
    ]
