# Generated by Django 5.2.13 on 2026-05-03 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_tripitinerary_transportsegment_itinerarystop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='booking_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='booking_owner',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='confirmation_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='supplier_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CommunicationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('proposal', 'Proposal'), ('payment', 'Payment Request'), ('travel_pack', 'Travel Pack'), ('follow_up', 'Follow-up')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_due', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.CharField(choices=[('none', 'No Response Needed'), ('awaiting', 'Awaiting Response'), ('responded', 'Responded'), ('action_required', 'Action Required')], default='awaiting', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.lead')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='crm.quote')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'kind'], name='crm_communi_lead_id_05dd9c_idx'), models.Index(fields=['status', 'response_status'], name='crm_communi_status_aed05d_idx'), models.Index(fields=['follow_up_due'], name='crm_communi_follow__37787e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('balance', 'Balance'), ('full', 'Full Payment'), ('refund', 'Refund')], default='deposit', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('proof_received', models.BooleanField(default=False)),
                ('proof_reference', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='crm.lead')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='crm.quote')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'status'], name='crm_payment_lead_id_7af179_idx'), models.Index(fields=['quote', 'status'], name='crm_payment_quote_i_f7a0ce_idx'), models.Index(fields=['due_date'], name='crm_payment_due_dat_c3999a_idx')],
            },
        ),
    ]
