# Generated by Django 5.2.13 on 2026-05-03 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_quoteline_booking_notes_quoteline_booking_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('blocker', 'Workflow Blocker'), ('follow_up', 'Follow-up'), ('payment_due', 'Payment Due'), ('booking_deadline', 'Booking Deadline'), ('travel_pack', 'Travel Pack')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('source_stage', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('communication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_reminders', to='crm.communicationrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_workflow_reminders', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_reminders', to='crm.lead')),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
                'indexes': [models.Index(fields=['lead', 'status'], name='crm_workflo_lead_id_6da43d_idx'), models.Index(fields=['reminder_type', 'status'], name='crm_workflo_reminde_9a5608_idx'), models.Index(fields=['due_at'], name='crm_workflo_due_at_8675ca_idx'), models.Index(fields=['source_stage'], name='crm_workflo_source__90104f_idx')],
            },
        ),
    ]
