# Generated by Django 5.2.13 on 2026-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_workflow_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ctm_request_reference',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
    ]
