# Generated by Django 5.2.13 on 2026-05-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_ctm_request_reference'),
        ('ctm', '0005_tripinvoice_trippayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to='ctm.companyaccount'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company_account', 'service_key'], name='crm_lead_company_a7e223_idx'),
        ),
    ]
