# Generated by Django 5.2.17 on 2026-09-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_company_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='submission_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='submission_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
