# Generated by Django 5.2.17 on 2026-09-22 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lead_submission_fingerprint_lead_submission_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=True)),
                ('region', models.CharField(choices=[('Europa', 'Europa'), ('África', 'África'), ('Ásia', 'Ásia'), ('Médio Oriente', 'Médio Oriente'), ('Américas', 'Américas')], max_length=30)),
                ('styles', models.JSONField(default=list, help_text='List of tags: Romance, Família, Cultura, Praia, Aventura, Compras, Iconic Trips')),
                ('hero', models.URLField(help_text='HTTPS photograph URL')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='List of HTTPS photograph URLs')),
                ('nights', models.PositiveSmallIntegerField(default=5)),
                ('departure', models.CharField(blank=True, max_length=120)),
                ('pt', models.JSONField(help_text='Portuguese content. Use Paris Essencial as a template.')),
                ('en', models.JSONField(help_text='English content. Use Paris Essencial as a template.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='experience_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.CreateModel(
            name='TravelExperienceRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.travelexperience')),
            ],
        ),
    ]
