# Generated by Django 5.2.17 on 2026-09-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_paris_essencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexperience',
            name='detail_hero',
            field=models.URLField(blank=True, help_text='Optional wide hero for the experience page. The discovery card keeps its own photograph.'),
        ),
    ]
