# Generated by Django 5.2.17 on 2026-09-22 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner_labels(apps, schema_editor):
    """Match legacy free-text owner labels to real users.

    Matches on username or "first last" full name, case-insensitive.
    Unmatched labels stay null, which the API surfaces as "Unassigned".
    """
    User = apps.get_model("auth", "User")
    users = list(User.objects.all())

    def match_user(label):
        label = (label or "").strip().lower()
        if not label:
            return None
        for user in users:
            if user.username.lower() == label:
                return user
            full_name = f"{user.first_name} {user.last_name}".strip().lower()
            if full_name and full_name == label:
                return user
        return None

    Client = apps.get_model("crm", "Client")
    QuoteLine = apps.get_model("crm", "QuoteLine")
    WorkflowReminder = apps.get_model("crm", "WorkflowReminder")

    for client in Client.objects.exclude(owner_label=""):
        client.owner = match_user(client.owner_label)
        client.save(update_fields=["owner"])

    for line in QuoteLine.objects.exclude(booking_owner_label=""):
        line.booking_owner = match_user(line.booking_owner_label)
        line.save(update_fields=["booking_owner"])

    for reminder in WorkflowReminder.objects.exclude(assigned_to_label=""):
        reminder.assigned_to = match_user(reminder.assigned_to_label)
        reminder.save(update_fields=["assigned_to"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_paris_detail_hero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='owner',
            new_name='owner_label',
        ),
        migrations.RenameField(
            model_name='quoteline',
            old_name='booking_owner',
            new_name='booking_owner_label',
        ),
        migrations.RenameField(
            model_name='workflowreminder',
            old_name='assigned_to',
            new_name='assigned_to_label',
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='booking_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_quote_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowreminder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_owner_labels, migrations.RunPython.noop),
    ]
