# Generated by Django 5.2.17 on 2026-10-05 04:05

from django.db import migrations, models


def backfill_task_fields(apps, schema_editor):
    """Migrate legacy reminder values onto the task model.

    - status "done" becomes "completed".
    - Existing rows came from the automation pipeline, so origin stays
      "system" (the field default).
    - Completion condition and waiting-on party are derived from the
      reminder type; follow-up tasks inherit the communication follow-up date.
    """
    WorkflowReminder = apps.get_model("crm", "WorkflowReminder")
    WorkflowReminder.objects.filter(status="done").update(status="completed")

    condition_by_type = {
        "payment_due": "payment_verified",
        "booking_deadline": "supplier_confirmed",
        "follow_up": "client_responded",
    }
    waiting_on_by_type = {
        "booking_deadline": "supplier",
        "follow_up": "client",
    }
    for reminder in WorkflowReminder.objects.select_related("communication"):
        reminder.completion_condition = condition_by_type.get(reminder.reminder_type, "none")
        reminder.waiting_on = waiting_on_by_type.get(reminder.reminder_type)
        if reminder.reminder_type == "follow_up" and reminder.communication_id and reminder.follow_up_at is None:
            reminder.follow_up_at = reminder.communication.follow_up_due
        reminder.save(update_fields=["completion_condition", "waiting_on", "follow_up_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_ownership_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowreminder',
            name='completion_condition',
            field=models.CharField(choices=[('none', 'None'), ('payment_verified', 'Payment Verified'), ('supplier_confirmed', 'Supplier Confirmed'), ('client_responded', 'Client Responded')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='workflowreminder',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowreminder',
            name='origin',
            field=models.CharField(choices=[('system', 'System'), ('manager', 'Manager'), ('automation', 'Automation')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowreminder',
            name='waiting_on',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('supplier', 'Supplier'), ('internal', 'Internal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workflowreminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_task_fields, migrations.RunPython.noop),
    ]
