# Generated by Django 5.2.13 on 2026-04-27 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('legal_name', models.CharField(blank=True, max_length=220)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('default_currency', models.CharField(default='USD', max_length=12)),
                ('service_level', models.CharField(choices=[('classic', 'Classic'), ('corporate', 'Corporate'), ('prestige_corporate', 'Prestige Corporate')], default='corporate', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_account', to='crm.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('travel_coordinator', 'Travel Coordinator'), ('manager', 'Manager'), ('finance_approver', 'Finance Approver'), ('company_admin', 'Company Admin')], default='employee', max_length=32)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='ctm.companyaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('passport_number', models.CharField(blank=True, max_length=80)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('passport_status', models.CharField(choices=[('ok', 'OK'), ('missing', 'Missing'), ('expired', 'Expired')], default='missing', max_length=20)),
                ('visa_status', models.CharField(choices=[('ok', 'OK'), ('required', 'Required'), ('pending', 'Pending'), ('n_a', 'Not applicable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='ctm.companyaccount')),
            ],
            options={
                'ordering': ['company__name', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('cost_center', models.CharField(blank=True, max_length=120)),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=180)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('budget_band', models.CharField(blank=True, max_length=80)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quoted_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('quote_ready', 'Quote ready'), ('final_approval', 'Final approval'), ('booked', 'Booked'), ('needs_documents', 'Needs documents'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=24)),
                ('request_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20)),
                ('approval_stage', models.CharField(choices=[('none', 'None'), ('travel_need', 'Travel need'), ('final_cost', 'Final cost')], default='none', max_length=20)),
                ('client_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to='ctm.companyaccount')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trip_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_requests', to='ctm.companyuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_type', models.CharField(choices=[('travel_need', 'Travel need'), ('final_cost', 'Final cost')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_approvals', to='ctm.companyuser')),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='ctm.triprequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('dpm', 'DPM'), ('company', 'Company'), ('system', 'System')], default='system', max_length=20)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('quote_sent', 'Quote sent'), ('documents_requested', 'Documents requested'), ('booked', 'Booked'), ('completed', 'Completed'), ('note', 'Note')], default='note', max_length=32)),
                ('visibility', models.CharField(choices=[('shared', 'Shared'), ('internal_only', 'Internal only')], default='shared', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_company_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='ctm.companyuser')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='ctm.triprequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripTraveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_status', models.CharField(choices=[('ready', 'Ready'), ('missing_passport', 'Missing passport'), ('visa_required', 'Visa required'), ('pending_docs', 'Pending documents')], default='ready', max_length=24)),
                ('special_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_assignments', to='ctm.traveler')),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_travelers', to='ctm.triprequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='triprequest',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='trip_requests', through='ctm.TripTraveler', to='ctm.traveler'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['status', 'service_level'], name='ctm_company_status_329bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['name'], name='ctm_company_name_6cbe5c_idx'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(fields=['company', 'role'], name='ctm_company_company_3ff8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(fields=['company', 'is_active'], name='ctm_company_company_9557ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyuser',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_company_user_membership'),
        ),
        migrations.AddIndex(
            model_name='traveler',
            index=models.Index(fields=['company', 'department'], name='ctm_travele_company_07c1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='traveler',
            index=models.Index(fields=['company', 'is_active'], name='ctm_travele_company_76aacd_idx'),
        ),
        migrations.AddIndex(
            model_name='traveler',
            index=models.Index(fields=['passport_status', 'visa_status'], name='ctm_travele_passpor_40e5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='tripapproval',
            index=models.Index(fields=['trip_request', 'status'], name='ctm_tripapp_trip_re_9c6895_idx'),
        ),
        migrations.AddIndex(
            model_name='tripapproval',
            index=models.Index(fields=['approval_type', 'status'], name='ctm_tripapp_approva_c56c34_idx'),
        ),
        migrations.AddIndex(
            model_name='triptimelineevent',
            index=models.Index(fields=['trip_request', 'created_at'], name='ctm_triptim_trip_re_7b8422_idx'),
        ),
        migrations.AddIndex(
            model_name='triptimelineevent',
            index=models.Index(fields=['event_type', 'visibility'], name='ctm_triptim_event_t_ad9182_idx'),
        ),
        migrations.AddIndex(
            model_name='triptraveler',
            index=models.Index(fields=['trip_request', 'document_status'], name='ctm_triptra_trip_re_ff5f4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='triptraveler',
            constraint=models.UniqueConstraint(fields=('trip_request', 'traveler'), name='unique_trip_request_traveler'),
        ),
        migrations.AddIndex(
            model_name='triprequest',
            index=models.Index(fields=['company', 'status'], name='ctm_tripreq_company_7dd5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='triprequest',
            index=models.Index(fields=['company', 'departure_date'], name='ctm_tripreq_company_c27193_idx'),
        ),
        migrations.AddIndex(
            model_name='triprequest',
            index=models.Index(fields=['requested_by', 'status'], name='ctm_tripreq_request_a787b1_idx'),
        ),
    ]
