# Generated by Django 5.2.13 on 2026-04-27 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('Flight', 'Flight'), ('Hotel', 'Hotel'), ('Transfer', 'Transfer'), ('Visa support', 'Visa support')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='triprequest',
            name='reference_code',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
        migrations.AddIndex(
            model_name='triprequest',
            index=models.Index(fields=['reference_code'], name='ctm_tripreq_referen_30655e_idx'),
        ),
        migrations.AddField(
            model_name='tripservice',
            name='trip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ctm.triprequest'),
        ),
        migrations.AddIndex(
            model_name='tripservice',
            index=models.Index(fields=['trip_request', 'service_type'], name='ctm_tripser_trip_re_c41ebd_idx'),
        ),
    ]
