# Generated by Django 5.2.13 on 2026-04-27 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctm', '0003_tripbooking_tripquote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('itinerary', 'Itinerary'), ('approval', 'Approval'), ('invoice', 'Invoice'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('requested', 'Requested'), ('received', 'Received'), ('verified', 'Verified'), ('issued', 'Issued')], default='missing', max_length=20)),
                ('visibility', models.CharField(choices=[('shared', 'Shared'), ('internal_only', 'Internal only')], default='shared', max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_documents', to='ctm.traveler')),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ctm.triprequest')),
                ('uploaded_by_company_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_trip_documents', to='ctm.companyuser')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_trip_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['trip_request', 'status'], name='ctm_tripdoc_trip_re_cacc35_idx'), models.Index(fields=['document_type', 'visibility'], name='ctm_tripdoc_documen_0a816d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('dpm', 'DPM'), ('company', 'Company'), ('system', 'System')], default='company', max_length=20)),
                ('visibility', models.CharField(choices=[('shared', 'Shared'), ('internal_only', 'Internal only')], default='shared', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_company_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_messages', to='ctm.companyuser')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_messages', to=settings.AUTH_USER_MODEL)),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ctm.triprequest')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['trip_request', 'created_at'], name='ctm_tripmes_trip_re_10d891_idx'), models.Index(fields=['visibility', 'sender_type'], name='ctm_tripmes_visibil_094a68_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('visibility', models.CharField(choices=[('shared', 'Shared'), ('internal_only', 'Internal only')], default='shared', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_company_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trip_tasks', to='ctm.companyuser')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_tasks', to=settings.AUTH_USER_MODEL)),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ctm.triprequest')),
            ],
            options={
                'ordering': ['status', 'due_date', '-updated_at'],
                'indexes': [models.Index(fields=['trip_request', 'status'], name='ctm_triptas_trip_re_6d443c_idx'), models.Index(fields=['visibility', 'priority'], name='ctm_triptas_visibil_6a2bad_idx')],
            },
        ),
    ]
