# Generated by Django 5.2.13 on 2026-04-28 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctm', '0004_tripdocument_tripmessage_triptask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_trip_invoices', to=settings.AUTH_USER_MODEL)),
                ('trip_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='ctm.triprequest')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('reconciled', 'Reconciled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ctm.tripinvoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_trip_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tripinvoice',
            index=models.Index(fields=['status', 'updated_at'], name='ctm_tripinv_status_f92998_idx'),
        ),
        migrations.AddIndex(
            model_name='tripinvoice',
            index=models.Index(fields=['invoice_number'], name='ctm_tripinv_invoice_2885da_idx'),
        ),
        migrations.AddIndex(
            model_name='trippayment',
            index=models.Index(fields=['invoice', 'status'], name='ctm_trippay_invoice_057588_idx'),
        ),
        migrations.AddIndex(
            model_name='trippayment',
            index=models.Index(fields=['payment_method', 'status'], name='ctm_trippay_payment_1ea44e_idx'),
        ),
        migrations.AddIndex(
            model_name='trippayment',
            index=models.Index(fields=['reference'], name='ctm_trippay_referen_86b116_idx'),
        ),
    ]
