# Generated by Django 5.2.13 on 2026-05-07 13:14

from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def normalize_company_code(value):
    return slugify(value or "").replace("-", "").upper()[:32]


def company_code_from_name(name):
    return normalize_company_code(name) or "DPM"


def populate_company_identity(apps, schema_editor):
    CompanyAccount = apps.get_model("ctm", "CompanyAccount")
    CompanyUser = apps.get_model("ctm", "CompanyUser")

    used_codes = set()
    for company in CompanyAccount.objects.order_by("name", "id"):
        base = company_code_from_name(company.name)
        code = base
        suffix = 2
        while code in used_codes:
            code = f"{base[: max(1, 32 - len(str(suffix)))]}{suffix}"
            suffix += 1
        company.account_code = code
        company.save(update_fields=["account_code"])
        used_codes.add(code)

    for membership in CompanyUser.objects.select_related("user").order_by("company_id", "created_at"):
        membership.login_username = membership.user.username
        membership.access_roles = [membership.role]
        membership.save(update_fields=["login_username", "access_roles"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_company_account'),
        ('ctm', '0005_tripinvoice_trippayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='account_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='access_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='login_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(populate_company_identity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='companyaccount',
            name='account_code',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['account_code'], name='ctm_company_account_48f275_idx'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(fields=['company', 'login_username'], name='ctm_company_company_a8bb60_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyuser',
            constraint=models.UniqueConstraint(fields=('company', 'login_username'), name='unique_company_login_username'),
        ),
    ]
