# Generated by Django 5.2.13 on 2026-05-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctm', '0006_companyaccount_account_code_companyuser_access_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripapproval',
            name='approval_type',
            field=models.CharField(choices=[('travel_need', 'Travel need'), ('briefing', 'Briefing'), ('final_cost', 'Final cost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='approval_stage',
            field=models.CharField(choices=[('none', 'None'), ('travel_need', 'Travel need'), ('briefing', 'Briefing'), ('final_cost', 'Final cost')], default='none', max_length=20),
        ),
    ]
